---
# tasks file for kvm

- name: Install kvm packages
  ansible.builtin.package:
    name: "{{ kvm_packages }}"
    state: present
    update_cache: yes

- name: Enable vhost_net module
  community.general.modprobe:
    name: vhost_net
    state: present
    persistent: present
  when:
    - kvm_vhost_net is defined
    - kvm_vhost_net is true

- name: Enable libvirtd service
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop: "{{ kvm_services }}"
  ignore_errors: "{{ ansible_virtualization_type in _container_types or ansible_connection in _container_types }}"

- name: Set selinux boolean values
  ansible.posix.seboolean:
    name: "{{ kvm_sebool_map[item] }}"
    state: "{{ vars[item] }}"
    persistent: yes
  when:
    - vars[item] is defined
    - ansible_selinux.status is defined
    - ansible_selinux.status == 'enabled'
  loop:
    - kvm_staff_use_svirt
    - kvm_unprivuser_use_svirt
    - kvm_virt_sandbox_use_audit
    - kvm_virt_sandbox_use_netlink
    - kvm_virt_sandbox_use_sys_admin
    - kvm_virt_transition_userdomain
    - kvm_virt_use_comm
    - kvm_virt_use_execmem
    - kvm_virt_use_fusefs
    - kvm_virt_use_nfs
    - kvm_virt_use_rawip
    - kvm_virt_use_samba
    - kvm_virt_use_sanlock
    - kvm_virt_use_usb
    - kvm_virt_use_xserver
  notify: Restart services

- name: "Create symlink from {{ kvm_qemu_link.src }} to {{ kvm_qemu_link.dest }}"
  ansible.builtin.file:
    src: "{{ kvm_qemu_link.src }}"
    dest: "{{ kvm_qemu_link.dest }}"
    owner: root
    group: root
    state: link
  when:
    - kvm_qemu_link is defined
    - kvm_qemu_link.src is defined
    - kvm_qemu_link.dest is defined

# Define a new network
- name: Create and set networks to autostart on boot
  when:
    - kvm_network_add is defined
    - kvm_network_add | length > 0
  block:
    - name: Define network
      community.libvirt.virt_net:
        command: define
        name: "{{ item.name }}"
        xml: '{{ lookup("template", "networks/{{ item.template }}") }}'
      loop: "{{ kvm_network_add }}"

    - name: Set network to autostart on boot
      community.libvirt.virt_net:
        autostart: yes
        name: "{{ item.name }}"
      loop: "{{ kvm_network_add }}"

    - name: Ensure network is active
      community.libvirt.virt_net:
        state: active
        name: "{{ item.name }}"
      loop: "{{ kvm_network_add }}"

# Remove a network
- name: Stop and remove networks
  when: kvm_network_remove is defined
  block:
    - name: Stop (destroy) network
      community.libvirt.virt_net:
        command: destroy
        name: "{{ item }}"
      loop: "{{ kvm_network_remove }}"
      ignore_errors: yes

    - name: Undefine network
      community.libvirt.virt_net:
        command: undefine
        name: "{{ item }}"
      loop: "{{ kvm_network_remove }}"

# POOLS
- name: Create and set pools to autostart on boot
  when: kvm_pool_add is defined
  block:
    - name: Define pool
      community.libvirt.virt_pool:
        command: define
        name: "{{ item.name }}"
        xml: '{{ lookup("template", "pools/{{ item.template }}") }}'
      loop: "{{ kvm_pool_add }}"

    - name: Set pool to autostart on boot
      community.libvirt.virt_pool:
        autostart: yes
        name: "{{ item.name }}"
      loop: "{{ kvm_pool_add }}"

    - name: Ensure pool is active
      community.libvirt.virt_pool:
        state: active
        name: "{{ item.name }}"
      loop: "{{ kvm_pool_add }}"

# Remove a pool
- name: Stop and remove pools
  when: kvm_pool_remove is defined
  block:
    - name: Stop (destroy) pool
      community.libvirt.virt_pool:
        command: destroy
        name: "{{ item }}"
      loop: "{{ kvm_pool_remove }}"
      ignore_errors: yes

    - name: Undefine pool
      community.libvirt.virt_pool:
        command: undefine
        name: "{{ item }}"
      loop: "{{ kvm_pool_remove }}"

 # VMs

- name: Copy virtual machine files to destination
  vars:
    # Check files is defined and have elements
    isempty: "{{ kvm_vm_add | selectattr('files', 'defined') | list | length == 0 }}"
    # Only call subelements if not empty, preventing error
    looplist: "{{ [] if isempty else kvm_vm_add | subelements('files') }}"
  ansible.builtin.copy:
    src: "{{ item.1.name }}"
    dest: "{{ item.1.dest }}"
    force: no
    owner: "{{ item.1.owner | default('root') }}"
    group: "{{ item.1.group | default('root') }}"
    mode: "{{ item.1.mode | default('0600') }}"
    remote_src: no
  when:
    - item.1.name is defined
    - item.1.name is file
    - item.1.dest is defined
    - item.1.dest | type_debug == 'str'
  loop: "{{ looplist }}"

 # Defining a VM and making is autostart with host. VM will be off after this task
- name: Define vm from xml and set autostart
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/libexec"
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'vms/{{ item.template }}') }}"
    autostart: "{{ item.autostart | default(false) }}"
  loop: "{{ kvm_vm_add | default([]) }}"

# Stop vm and undefine it
- name: Stop VMs and undefine them
  when: kvm_vm_remove is defined
  block:
    - name: Stop (destroy) vm
      community.libvirt.virt:
        command: destroy
        name: "{{ item }}"
      loop: "{{ kvm_vm_remove }}"
      ignore_errors: yes

    - name: Undefine vm
      community.libvirt.virt:
        command: undefine
        name: "{{ item }}"
      loop: "{{ kvm_vm_remove }}"
